language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer selfupdate
  - composer install

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
